.DEFAULT_GOAL := build

setup:
	./gradlew wrapper --gradle-version 8.5

clean:
	./gradlew clean

install:
	./gradlew installDist

run:
	./gradlew run

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

lint:
	./gradlew checkstyleMain

.PHONY: build
